/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LoginByAccount: typeof import('./components/auth/LoginByAccount.vue')['default']
    LoginByPhone: typeof import('./components/auth/LoginByPhone.vue')['default']
    LoginByQrcode: typeof import('./components/auth/LoginByQrcode.vue')['default']
    LoginPanel: typeof import('./components/auth/LoginPanel.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NFloatButton: typeof import('naive-ui')['NFloatButton']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputOtp: typeof import('naive-ui')['NInputOtp']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NQrCode: typeof import('naive-ui')['NQrCode']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NTab: typeof import('naive-ui')['NTab']
    NTabs: typeof import('naive-ui')['NTabs']
    NTooltip: typeof import('naive-ui')['NTooltip']
    PreferenceButton: typeof import('./components/common/PreferenceButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeProvider: typeof import('./components/common/ThemeProvider.vue')['default']
    ThemeSwitcher: typeof import('./components/common/ThemeSwitcher.vue')['default']
  }
}

// For TSX support
declare global {
  const LoginByAccount: typeof import('./components/auth/LoginByAccount.vue')['default']
  const LoginByPhone: typeof import('./components/auth/LoginByPhone.vue')['default']
  const LoginByQrcode: typeof import('./components/auth/LoginByQrcode.vue')['default']
  const LoginPanel: typeof import('./components/auth/LoginPanel.vue')['default']
  const NAvatar: typeof import('naive-ui')['NAvatar']
  const NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
  const NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
  const NButton: typeof import('naive-ui')['NButton']
  const NCard: typeof import('naive-ui')['NCard']
  const NDropdown: typeof import('naive-ui')['NDropdown']
  const NFloatButton: typeof import('naive-ui')['NFloatButton']
  const NForm: typeof import('naive-ui')['NForm']
  const NFormItem: typeof import('naive-ui')['NFormItem']
  const NGradientText: typeof import('naive-ui')['NGradientText']
  const NH2: typeof import('naive-ui')['NH2']
  const NIcon: typeof import('naive-ui')['NIcon']
  const NInput: typeof import('naive-ui')['NInput']
  const NInputOtp: typeof import('naive-ui')['NInputOtp']
  const NLayout: typeof import('naive-ui')['NLayout']
  const NLayoutContent: typeof import('naive-ui')['NLayoutContent']
  const NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
  const NLayoutSider: typeof import('naive-ui')['NLayoutSider']
  const NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
  const NMenu: typeof import('naive-ui')['NMenu']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
  const NQrCode: typeof import('naive-ui')['NQrCode']
  const NScrollbar: typeof import('naive-ui')['NScrollbar']
  const NTab: typeof import('naive-ui')['NTab']
  const NTabs: typeof import('naive-ui')['NTabs']
  const NTooltip: typeof import('naive-ui')['NTooltip']
  const PreferenceButton: typeof import('./components/common/PreferenceButton.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const ThemeProvider: typeof import('./components/common/ThemeProvider.vue')['default']
  const ThemeSwitcher: typeof import('./components/common/ThemeSwitcher.vue')['default']
}